---
cluster:
  hosts:
    fundament.unordnung.org:
      ansible_user: root
      ansible_host: fundament.unordnung.org
      ansible_port: 15922
      ansible_ssh_private_key_file: /Users/kai/.ssh/id_rsa
      host: fundament
      hostname: fundament.unordnung.org
      swarm_node:
        labels:
          type: manager
          env: production

  children:
    cluster_managers:
      children:
        cluster_manager:
          hosts:
            fundament.unordnung.org:

        cluster_managers_additional:
          hosts:

    cluster_workers:
      hosts:
