; This is a mxdev configuration file
; it can be used to override versions of packages already defined in the
; constraints files and to add new packages from VCS like git.
; to learn more about mxdev visit https://pypi.org/project/mxdev/

[settings]
main-package = -e .[test]
; example how to override a package version
; version-overrides =
;     example.package==2.1.0a2

offline = true 

; example section to use packages from git
; [example.contenttype]
; url = https://github.com/collective/example.contenttype.git
; pushurl = git@github.com:collective/example.contenttype.git
; extras = test
; branch = master
[Products.EasyNewsletter]
url = https://github.com/collective/Products.EasyNewsletter.git
branch = master
use = True

[plone.gallery]
url=https://github.com/plone/plone.gallery.git
branch = master
use = True

[collective.contentrules.mailtogroup]
url=https://github.com/collective/collective.contentrules.mailtogroup
branch = py3-1letter
use = True
